apiVersion: v1
kind: Service
metadata:
  name: saraswati-editofhir-converter-service
spec:
  selector:
    app: saraswati-editofhir-converter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080